### ISSUE TITLE
'unable to parse env variables for psctl image' when following Dark-Site installation process

### ISSUE THREAD

**Issue by eRaid6** [purestorage/pso-csi#116]
When following the [Dark Site installation](https://github.com/purestorage/pso-csi/tree/master/pure-pso#dark-site-installation) process and using [mirror_pso_containers.sh](https://raw.githubusercontent.com/purestorage/pso-csi/master/mirror_pso_containers.sh) I get the following error on the cockroach operator and the installation stops progressing.  All of the images are successfully pulled from the internal registry.
```
$ oc get pods
NAME                                         READY   STATUS             RESTARTS   AGE
pso-csi-controller-0                         5/6     Running            5          3m24s
pso-csi-node-8zjm9                           2/3     Running            5          3m24s
pso-csi-node-dwzht                           2/3     Running            5          3m24s
pso-csi-node-td2rj                           2/3     Running            5          3m24s
pso-db-cockroach-operator-7d8469c9c8-smcpq   0/1     CrashLoopBackOff   5          3m24s
pso-db-deployer-778f97db5b-ckp8g             1/1     Running            0          3m24s

$ oc logs pso-db-cockroach-operator-7d8469c9c8-smcpq -n pure-pso                                                                         
{"level":"info","ts":1605907706.4262958,"logger":"cmd","msg":"","is_debug_mode":false}
{"level":"info","ts":1605907706.4263296,"logger":"cmd","msg":"Go Version: go1.15"}
{"level":"info","ts":1605907706.4263344,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1605907706.4263387,"logger":"cmd","msg":"Version of operator-sdk: v0.6.0"}
{"level":"error","ts":1605907706.426353,"logger":"cmd","msg":"unable to parse env variables for psctl image","error":"psctl image tag was specified as both gitlab.example.com:5005/oscp/pure-pso/psctl and v1.0.1","st
acktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/pso.purestorage.com/cockroach-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.parseEnv\n\t/go/src/pso.purestorage.com/cockroach-operator/
cmd/cockroach-operator/main.go:152\nmain.main\n\t/go/src/pso.purestorage.com/cockroach-operator/cmd/cockroach-operator/main.go:269\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204"}```

**Comment by Pure-AdamuKaapan** [comment]
Hello @eRaid6 ! Would I be able to see your `values.yaml` (specifically the `images` stanza). Thank you!

**Comment by eRaid6** [comment]
Hi @Pure-AdamuKaapan here is the `images` section of `values.yaml`
```
images: 
  plugin:                                                                       
    name: gitlab.example.com:5005/oscp/pure-pso/k8s                             
    tag: v6.0.3                                                                 
    pullPolicy: Always                                                          
  csi:                                                                          
    provisioner:                                                                
      name: gitlab.example.com:5005/oscp/pure-pso/k8scsi/csi-provisioner        
      pullPolicy: Always                                                        
    snapshotter:                                                                
      name: gitlab.example.com:5005/oscp/pure-pso/k8scsi/csi-snapshotter        
      pullPolicy: Always                                                        
    attacher:                                                                   
      name: gitlab.example.com:5005/oscp/pure-pso/k8scsi/csi-attacher           
      pullPolicy: Always                                                        
    resizer:                                                                    
      name: gitlab.example.com:5005/oscp/pure-pso/k8scsi/csi-resizer            
      pullPolicy: Always                                                        
    nodeDriverRegistrar:                                                        
      name: gitlab.example.com:5005/oscp/pure-pso/k8scsi/csi-node-driver-registrar
      pullPolicy: Always                                                        
    livenessProbe:                                                              
      name: gitlab.example.com:5005/oscp/pure-pso/k8scsi/livenessprobe          
      pullPolicy: Always                                                        
  database:                                                                     
    deployer:                                                                   
      name: gitlab.example.com:5005/oscp/pure-pso/dbdeployer                    
      tag: v1.0.3                                                               
      pullPolicy: Always                                                        
    cockroachOperator:                                                          
      name: gitlab.example.com:5005/oscp/pure-pso/cockroach-operator            
      tag: v1.0.3                                                               
      pullPolicy: Always                                                        
    psctl:                                                                      
      name: gitlab.example.com:5005/oscp/pure-pso/psctl                         
      tag: v1.0.1                                                               
    cockroachdb:                                                                
      name: gitlab.example.com:5005/oscp/pure-pso/cockroach                     
      tag: v19.2.3
```

**Comment by Pure-AdamuKaapan** [comment]
Ohhhh, I think I see what's happening. When I set up the parsing for this, I forgot that you may need port numbers in the registry address, and we had it set up to be a little "smarter", so that if you specified the tag in the name it would split it out. This should be fixable by making it use only the last section split by colons for the tag and joining the rest back together.

I'll shoot to have a fix in early next week, which should be incorporated in the next release soon.

**Comment by eRaid6** [comment]
@Pure-AdamuKaapan  awesome thanks for the quick response!  When you have the patch ready let me know and I can test it out.

**Comment by Pure-AdamuKaapan** [comment]
@eRaid6 just FYI: there was a release (6.0.4) already in progress, so this fix won't be included in that. It will be picked up by the next release (either 6.0.5 or 6.1.0, whichever comes first)

**Comment by eRaid6** [comment]
@Pure-AdamuKaapan  sounds good.  This fix is to the `psctl` image correct, so no workaround possible at this point I assume?

**Comment by Pure-AdamuKaapan** [comment]
@eRaid6 correct; at the moment I can't think of any workaround unless you're able to remove the port.

**Comment by eRaid6** [comment]
@Pure-AdamuKaapan unfortunately our GitLab registry listens on [port 5005](https://docs.gitlab.com/ee/administration/packages/container_registry.html#enable-the-container-registry) (the default) and `docker push` uses the private registry hostname and port that the image is tagged with so if I do not tag the image with the port when I go to push the image I get `Error: Status 404 trying to push repository oscp/pure-pso/psctl` error which is seemingly expected since I did not specify the port the registry is listening on.

I guess that's a long winded way of me agreeing I do not know of any workaround currently.

**Comment by haibinxie** [comment]
@eRaid6 we are planning to include the fix in next release, hopefully will be released on coming Monday or Tuesday. Before the release, Could you try these builds and see if they work for you?

  plugin:
    name: purestorage/k8s
    tag: v6.0.4
    pullPolicy: Always
  database:
    deployer:
      name: purestorage/dbdeployer
      tag: v1.0.4
      pullPolicy: Always
    cockroachOperator:
      name: purestorage/cockroach-operator
      tag: v1.0.4
      pullPolicy: Always
    psctl:
      name: purestorage/psctl
      tag: v1.0.2

**Comment by eRaid6** [comment]
@haibinxie I tested the containers above.  When I switch to those versions the pso-csi-node containers are in a restart loop and have the following error
```
$ oc logs pso-csi-node-f9222 node-driver-registrar
I1130 15:45:25.218602   34609 main.go:110] Version: v1.3.0-0-g6e9fff3e
I1130 15:45:25.218696   34609 connection.go:151] Connecting to unix:///csi/csi.sock
I1130 15:45:25.221167   34609 node_register.go:51] Starting Registration Server at: /registration/pure-csi-reg.sock
I1130 15:45:25.221333   34609 node_register.go:60] Registration Server started at: /registration/pure-csi-reg.sock
I1130 15:45:26.235410   34609 main.go:77] Received GetInfo call: &InfoRequest{}
I1130 15:45:26.587674   34609 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: error updating Node object with CSI driver node info: error updating node: timed out waiting for the condition; caused by: detected topology value collision: driver reported "nodeID":"compute1-example-com" but existing label is "nodeID":"compute1.example.com",}
E1130 15:45:26.587767   34609 main.go:89] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: error updating Node object with CSI driver node info: error updating node: timed out waiting for the condition; caused by: detected topology value collision: driver reported "nodeID":"compute1-example-com" but existing label is "nodeID":"compute1.example.com", restarting registration container.
```

Let me know if I can provide any more information to help root cause this issue.

**Comment by david-enli** [comment]
Hi Nick, are you using the topology feature? If so, would you be able to share you topology labels with us? Thanks

En

**Comment by eRaid6** [comment]
Hi @david-enli  I am not using the topology feature.
```
# this option is to enable/disable the csi topology feature                     
# for pso-csi                                                                   
storagetopology:                                                                
  enable: false                                                                 
  strictTopology: false
```
