### ISSUE TITLE
Topology not working?

### ISSUE THREAD

**Issue by jake2184** [purestorage/pso-csi#148]
I'm having difficulty getting the CSI topology to work correctly. I have two Pure FlashBlades in separate racks, with a node in each rack, and am trying to get pods to get PVs on the Pure in the same rack.

Version is pure-csi v6.1.0, cluster is okd 4.7.0.

I have re-run the helm chart to update the flashblade labels:
```
arrays:
  FlashArrays: []
  FlashBlades:
    - MgmtEndPoint: "10.13.6.47"
      APIToken: **
      NFSEndPoint: 10.13.10.1
      Labels:
        topology.purestorage.com/rack: "rack-1"
    - MgmtEndPoint: "10.13.6.50"
      APIToken: **
      NFSEndPoint: 10.13.10.2
      Labels:
        topology.purestorage.com/rack: "rack-2"
```

and labelled my nodes:
```
jreynolds@laptop helm$ oc get node openshift-01 -oyaml | grep purestorage
    topology.purestorage.com/rack: rack-1
jreynolds@laptop helm$ oc get node openshift-02 -oyaml | grep purestorage
    topology.purestorage.com/rack: rack-2
```

and added a delayed pure-file storage class
```
jreynolds@laptop eqty3-oshift$ oc get storageclass
NAME                      PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
pure-block                pure-csi      Delete          Immediate              true                   7d3h
pure-file                 pure-csi      Delete          Immediate              true                   7d3h
pure-file-delay-binding   pure-csi      Delete          WaitForFirstConsumer   false                  3h39m
```

I've then created a stateful set with 5 replicas, each of which is scheduled to a node with a PVC of type pure-file-delay-binding.
```
  volumeClaimTemplates:
    - metadata:
        name: webserver-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: pure-file-delay-binding
        resources:
          requests:
            storage: 1Gi

# oc get pv
pvc-df23b3d4-296c-4fd4-85cf-c8c4f60319d4   1Gi        RWO            Delete           Bound    infra/webserver-data-webserver-statefulset-4      pure-file-delay-binding            113m
pvc-e0fa19c6-c3a6-4a98-974d-ac8acb3c9673   1Gi        RWO            Delete           Bound    infra/webserver-data-webserver-statefulset-0      pure-file-delay-binding            121m
pvc-fed6d8e7-dd5d-4a90-a457-58cfb2cca7f9   1Gi        RWO            Delete           Bound    infra/webserver-data-webserver-statefulset-1      pure-file-delay-binding            119m

```

However, I'm seeing all of my PVs created on the second Pure device, the one in "rack-2", regardless of if the pod is scheduled on node -01 or node -02. I'm expecting pods scheduled on node -01 get PVs created on the Pure device in rack-1, but this doesn't seem to be happening.

Have I missed a configuration step? I'm assuming the functionality is the same for pure-file as it is for the documented pure-block.
