### ISSUE TITLE
databases tolerations not added for pso-db pods

### ISSUE THREAD

**Issue by ralmn** [purestorage/pso-csi#176]
When we set the values.yaml with this settings:  

```yaml
database:
  # nodeSelector is the simplest way to limit which kubernetes nodes will run the database-related pods
  # Please refer to the top-level description of nodeSelector for an example
  nodeSelector:
    node.is.dtr: "yes"
  tolerations:
    - operator: Exists
      effect: "NoSchedule"
    - operator: Exists
      effect: "NoExecute"
    - operator: Exists
      effect: "NoSchedule"
      key: "com.docker.ucp.manager"
```

The tolerations doesn't add on pso-db pods. So we cannot schedule pso-db on some nodes. 

We currently used the charts from master branch.
